%YAML:1.0

---

PathRec: "/localresearch/PreciseLocalization/Dataset/YuQuanMultimodal/T3-Lib-res-a-rgb/reference"
PathTest: "/localresearch/PreciseLocalization/Dataset/YuQuanMultimodal/T3-Lib-res-a-rgb/query"

# read "Feature" from files
FileType: 1
Interval: 1

cx: 161.5
cy: 119.8
fx: 288.4
fy: 288.4

# whether use color image
Color: 1
# other sensor
GPS: 1

