%YAML:1.0

---

PathRec: "/localresearch/PreciseLocalization/Dataset/YuQuanMultimodal/Gate-T3/database"
PathTest: "/localresearch/PreciseLocalization/Dataset/YuQuanMultimodal/Gate-T3/query"
#PathRec: "D:\\2015 Highway Dataset\\Day-netVLAD-patch"
#PathTest: "D:\\2015 Highway Dataset\\Night-netVLAD-patch"

# read "Feature" from files
FileType: 1
Interval: 1

# whether use color image
Color: 1
# other sensor
GPS: 0

