%YAML:1.0

---

PathRec: "H:\\YuquanPAL4Localization\\ProcessedDataset\\features_4parts\\Afternoon1"
PathTest: "H:\\YuquanPAL4Localization\\ProcessedDataset\\features_4parts\\Dusk1"
#PathRec: "D:\\2015 Highway Dataset\\Day-netVLAD-patch"
#PathTest: "D:\\2015 Highway Dataset\\Night-netVLAD-patch"

# read "Feature" from files
FileType: 1
Interval: 1

# whether use color image
Color: 1
# other sensor
GPS: 0

