%YAML:1.0

---

PathRec: "/localresearch/VisualLocalization/Dataset/Self-collected/HangzhouCity/Ret/westlake-5-scene10/database"
PathTest: "/localresearch/VisualLocalization/Dataset/Self-collected/HangzhouCity/Ret/westlake-5-scene10/query"
RetPath: "/localresearch/VisualLocalization/Dataset/Self-collected/HangzhouCity/Ret/westlake-5-scene10"

# FileType: read "Feature" from files, true=feature, false=image
FileType: 1
Interval: 1

# Parameters of Image Retrieval
TopK: 10
UseSceneNum: 5

# Parameters of sequence searching
n_q: 10
online: 1
v_max: 2.5
v_min: 0.4

window: 10
ratioTh: 2







