%YAML:1.0

---

PathRec: "/localresearch/VisualLocalization/Dataset/dataset GardensPointWalking/day/database"
PathTest: "/localresearch/VisualLocalization/Dataset/dataset GardensPointWalking/day/query"
RetPath: "/localresearch/VisualLocalization/Dataset/dataset GardensPointWalking/day"

# FileType: read "Feature" from files, true=feature, false=image
FileType: 1
Interval: 1

# Parameters of Image Retrieval
TopK: 10
UseSceneNum: 5

# Parameters of sequence searching
n_q: 10
online: 1
v_max: 2.5
v_min: 0.4

window: 10
ratioTh: 1.2







