%YAML:1.0

---

PathRec: "/localresearch/VisualLocalization/Dataset/YuQuanMultimodal/T3-T3-vgg-a/reference"
PathTest: "/localresearch/VisualLocalization/Dataset/YuQuanMultimodal/T3-T3-vgg-a/query"

# read "Feature" from files
FileType: 1
Interval: 1

cx: 161.5
cy: 119.8
fx: 288.4
fy: 288.4

# other sensor
GNSS: 1
GNSSthres: 15

# Retrieval 
topK: 5

# Geometric Verification
Depth: 1
KeyPointGridSize: 4
minInlierNum: 300

# Sequence Matching 
num_queue: 10